### ISSUE TITLE
[meta] Feature Freeze

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#25]
- [x] ~~Define DB Schema for Project A #20~~
- [x] ~~Export Crawler init functions~~
- [x] Export Crawler update functions
- [x] Define CSV API
- [x] Export Function to render chart for one Character
- [x] ~~¿ List of most popular characters (or are they just using the DB) ? #18~~
- [x] JS / CSS files which have to be included || Function to set path so that we get them right in our Views

See https://github.com/Rostlab/JS16_ProjectD_Group4/milestones/Feature%20freeze

**Comment by julienschmidt** [comment]
## Preliminary API draft

### Config
- Twitter API key
- DB URI for Tweets
- CSV Path (Where should the generated CSV files be saved?)
- Optional: extend / overwrite crawling whitelist & blacklist

### JS API

``` js
// overwrite default settings, set API key etc
cfg              // attribute, not a function! defaults to defaults.json
cfg.extend(json) // merges JSON / appends lists

// update all or one specific character (recrawl, update CSVs, update character(s) in DB)
// set full=true to make a full recrawl instead of an incremental update
update(full=false)              // returns a Promise for sync
updateCharacter(id, full=false) // returns a Promise for sync

// get data for one specific character
character(id): Promise<{
  slug: String,
  total: Number,      // total number of tweets
  heat: Number,       // how much / how heated is the character discussed lately?
  negative: Number,   // number of total negative tweets
  positive: Number,   // number of total positive tweets
  popularity: Number  // how popular is this character lately?
}>

// get most interesting characters. n (number) is optional
// all functions return a Promise for an array of characters [see above]
mostPopular(n=10)
leastPopular(n=10) | mostHated(n=10)
mostDiscussed(n=10) | mostHeated(n=10)

// assets
// absolute path to css file
css.path
// http handler which returns the content of the css file
css.serve(req,res)
// absolute path to css file
js.path
// http handler which returns the content of the css file
js.serve(req,res)
```

### CSV API

The CSV API is used by chart.js

##### Episodes (all):

 `/csv/episodes.csv`

##### Data per Character:

```
/csv/Donald-Trump.csv               (complete overview, grouped per day)
/csv/Donald-Trump/2016-03.csv       (month overview, grouped per hour)
```

### How to display a chart:

The following files have to be served:
- D3.js
- chart.js
- chart.css

Then include a tag like this in the HTML body:
`<svg id="chart"></svg>`

##### Initialize chart:

``` js
var chart = characterChart(d3.select("#chart"), "/donald-trump/");
d3.select(window).on('resize', chart.resize); // optional
```

##### ToDo:
- how to pass CSV path to the chart func?
- zoom level ?
- compare characters ?
- Where is the Streaming API registered?

**Comment by julienschmidt** [comment]
work ~~in progress~~: #56
